espressomd/espresso

src/tcl/particle_data_tcl.cpp, testsuite/engine_langevin.tcl
The bug crashed the compilation of ESPResSo when the following configuration in myconfig.hpp was met:
#define ENGINE
//#define LB
//#define LB_GPU
//#define LB_BOUNDARIES
//#define LB_BOUNDARIES_GPU
=> ENGINE feature: Fixed a bug in the interface and in the test case.

src/core/communication.cpp
The forces are scaled by the masses and the time step in the output, i.e. `part 0 print f`, but are not scaled by the mass in the input, i.e. `part 0 f`.
=> Force scaling is wrong on TCL level

src/core/electrokinetics_cuda.cu, src/core/lbgpu_cuda.cu
Only remaining occurences are related to the radial_profile_data struct typedef, which contains doubles and is also used in host code.
On remaining strangeness is a large number of cvt.f64.f32 immediately followed by cvt.rn.f32.f64 instructions:
```
//specfunc_cuda.hpp:175   return x*d - dd + c[0]/2;
.loc	3 175 1
mul.f32 	%f10, %f7, %f5;
sub.f32 	%f11, %f10, %f4;
ld.f32 	%f12, [%rd1];
cvt.f64.f32	%fd1, %f12;
cvt.rn.f32.f64	%f13, %fd1;
tmp22:
mov.f32 	%f14, 0f40000000;
mov.f32 	%f15, %f14;
tmp23:
//specfunc_cuda.hpp:175   return x*d - dd + c[0]/2;
.loc	3 175 106
bra.uni	tmp24;
tmp24:
///usr/local/cuda/bin/..//include/device_functions.h:3608   return a / b;
.loc	4 3608 3
div.rn.f32 	%f16, %f13, %f15;
tmp25:
//specfunc_cuda.hpp:175   return x*d - dd + c[0]/2;
.loc	3 175 106
add.f32 	%f17, …
```
=> Remove some unnecessary usage of double precision instructions in CUDA code

src/python/espressomd/particle_data.pxd
Reported to me by @tomspur, found on Fedora, details here: http://koji.fedoraproject.org/koji/buildinfo?buildID=619654.
It might be time for a new release, too!
=> fix build with cython-0.22

src/core/forces_inline.hpp
The commit is pretty straightforward, it repairs a weird mass dependence of the force-swimming in case the Langevin thermostat is switched on. Fix does not alter the behavior of the test cases.
=> ENGINE: Repaired mass dependence in the Langevin swimmer.

src/core/integrate.cpp
Bugfix: some variable initialization was missing when both NPT and MULTI_TIMESTEP was turned on.
=> Fixed missing variable definition for MULTI_TIMESTEP

doc/ug/setup.tex, src/core/thermostat.cpp, src/core/thermostat.hpp, src/tcl/thermostat_tcl.cpp, testsuite/mass-and-rinertia.tcl
In this pull request, I have modified the behavior of the Langevin Thermostat, such that it now produces 'physically reasonable' behavior when specifying a proper friction coefficient. I've added a warning message in the code, such that the new behavior does not lead to confusion for the users and I have also documented the changes thoroughly in the User's Guide. I had to modify one of the test cases, which exploited the questionable behavior to reduce the execution time, but this one still verifies the important physics. I tried to run the full multi-config on my computer, but it failed due to quota issues, so I would recommend checking this before pulling my change into master.
=> Fix to the Langevin Dynamics bug

src/core/cuda_common_cuda.cu
the sc_affinity_gpu.tcl test was failing when VIRTUAL_SITES_RELATIVE was compiled in. It turned out that memory for torques in cuda_common_cuda.cu was not allocated, as the code checked only for DIPOLES, and not for ROTATION (required by the virtual sites).
=> fixed #ifdef for rotations in cuda

doc/ug/part.tex
From the text, it was not clear that, that the distance is measured in the direction of the normal vector. Although this seems to be clear, if the normal vector points away from the origin, it makes a huge different in the contrary case. Imagine a wall with normal (0,0,-1). In order to place it at z=5, the distance has to be set to -5. 
It is worth emphasizing this.
=> Little addittion to wall constraint

src/core/constraint.cpp
- Corrected copy-paste-typo, leading to incorrect values in the force calculation (in the order of double numeric limit).
- Suggest to delete irrelevant calculation cases. Since the pore is created with (numerical) infinite outer radius (c2_or), the only cases where the corresponding condition is true is r=std::numeric_limits<double>max(), which should not occur in simulation.s
=>  Review and correction of pore distance calculations. 

src/core/forces_inline.hpp
This is a revert of an original fix, which was made because the Langevin thermostat was broken at the time.
=> Fix for ENGINE feature

doc/tutorials/02-charged_system/02-charged_system.tex, doc/tutorials/02-charged_system/scripts/analyze.tcl, doc/tutorials/02-charged_system/scripts/analyze_rho.tcl, doc/tutorials/02-charged_system/scripts/replay.tcl
I've updated and checked the 02-charged_system tutorial and confirmed all the scripts work with the current Espresso master.
The only remaining issue is that the tutorial makes use of the undocumented `bin` command, see #409. While that command does its job just fine, it's not exactly good style to be using undocumented features in a tutorial.
=> Update the 02-charged_system tutorial

.travis.yml, maintainer/travis/build.sh
This might be pretty much useful to pinpoint which parts of the code need a test to be added to the testsuite. 
After the discussion during the developer meeting, I looked around for some solution that could help tracing how good the testcases are. There are several options around to integrate the CI builds with output from code coverage tools, such as [gcov](https://en.wikipedia.org/wiki/Gcov). I found particularly simple to add in travis support for [codecov](https://codecov.io).
With this patch I added code coverage to one of the element of the travis matrix. The outcome can be seen, for example, in this snapshot:
You can have a look directly at [the annotated code files of this patch](https://codecov.io/github/Marcello-Sega/espresso/src/core/integrate.cpp?ref=1c74fd659c32bdde7b5c490052 …
=> Added codecov support

src/core/Vector.hpp
initializer_list is a C++11 header. Even if you don't use anything from inside it, the compiler might give you an error if you include it but don't turn on C++11.
Original issue observed on GCC 4.8 with explicitly-disabled C++11.
=> Fix Vector.hpp without C++11

src/core/actor/DipolarDirectSum.cpp, src/core/actor/DipolarDirectSum.hpp, src/core/actor/DipolarDirectSum_cuda.cu, testsuite/Makefile.am, testsuite/dawaanr-and-dds-gpu.tcl
1. Avoid invalid frees
2. Missing Bjerum length (From B.M Tanygin, pull request #453 
3. Testcase comparing dipolar direct summation methods against each other and checking the scaling with Bjerrum length
=> Fixes bugs in dipolar direct sum on gpu

src/tcl/statistics_tcl.cpp
Espresso will write out a warning to stderr whenever an analyze command is called, for which there is no documentation, nor a test case available. See open issues.
I also noticed that there might be problems with naming future commands if ARG1_IS_S is used, since it only requires the given command string to only match the first letters of the required string instead of matching exactly with the required string. This might cause the wrong function to be called. It can be dealt with by using ARG1_IS_S_EXACT, but since I don't know whether or not this is intentional, I didn't changed it.
=> Deprecation warnings for undocumented analyze cmds

testsuite/bonded_coulomb.tcl, testsuite/ek_electrostatics_coupling_x.tcl, testsuite/ek_electrostatics_coupling_y.tcl, testsuite/ek_electrostatics_coupling_z.tcl
expr $a - $b is only valid syntax for $b >= 0 because TCL sucks
** requires TCL >= 8.5
=> missing () and ** instead of pow() in testcases

src/python/espressomd/actors.pyx, src/python/espressomd/analyze.pyx, src/python/espressomd/code_info.pyx, src/python/espressomd/electrostatic_extensions.pyx, src/python/espressomd/electrostatics.pxd, src/python/espressomd/integrate.pyx, src/python/espressomd/interactions.pyx, src/python/espressomd/lb.pyx, src/python/espressomd/magnetostatic_extensions.pyx, src/python/espressomd/magnetostatics.pyx, src/python/espressomd/particle_data.pxd, src/python/espressomd/particle_data.pyx, src/python/espressomd/thermostat.pyx, testsuite/python/cellsystem.py, testsuite/python/electrostaticInteractions.py, testsuite/python/ewald_gpu.py, testsuite/python/magnetostaticInteractions.py, testsuite/python/nonBondedInteractions.py, testsuite/python/p3m_gpu.py, testsuite/python/particle.py
This one is rebased to the pep8 naming convention refactor (#487), and needs to be merged after that one.
=> Python bond fixes/extensions the 2nd

src/core/electrokinetics.hpp, src/python/espressomd/electrokinetics.pyx
Importing the electrokinetics module raised an undefined symbol error.
Needs to be tested when EK_REACTION works in python.
=> Fixed ek_..._reaction_tag undefined symbol error

doc/ug/inter.tex, src/core/initialize.cpp
This commit fixes the mmm1dgpu energy calculation if the particle number change in the simulation. Prior to this commit the particle number for the GPU code has never changed.
=> update particle numbers on the GPU on particle change

samples/python/not-working/globals.py, samples/python/not-working/hello_parallel_world.py, samples/python/not-working/thermostat_test.py, src/core/communication.cpp, src/python/espressomd/__init__.py
The real issue underlying #404 is that each Python module is statically linked against libEspresso. Because we use `dlopen` with `RTLD_GLOBAL`, nobody noticed it yet.
This is a pull request that removes `RTLD_GLOBAL` except for when used with OpenMPI. Before merging it, you need to modify the build system so that libEspresso, libEspressoTcl and libEspressoTcl4Py are built as shared libraries instead of as static libraries. Besides, you need to add `-ldl` to the `LDFLAGS` when building with OpenMPI. I tried to do that myself, but my automake+libtool skills are insufficient.
=> Remove RTLD_GLOBAL for all libraries except OpenMPI

src/core/particle_data.cpp
particle_exists() does not depend on the ROTATIONAL_INTERTIA feature.
Fixes the problem of the python interface (if built without ROTATIONAL_INTERTIA):
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "espressomd/__init__.py", line 33, in <module>
from espressomd.system import System
File "espressomd/system.py", line 3, in <module>
from espressomd import _system
File "espressomd/_system.pyx", line 27, in init espressomd._system (_system.cpp:7031)
import particle_data
ImportError: espressomd/particle_data.so: undefined symbol: _Z15particle_existsi
=> Pull particle_exists (particle_data.cpp) out of the #ifdef

configure.ac, src/core/communication.cpp, src/core/forces_inline.hpp, src/core/particle_data.cpp, src/core/particle_data.hpp, src/python/espressomd/Makefile.am, src/tcl/Makefile.am
- Close unterminated comment
- Workaround for missing symbol ParticleProperties::mass
- Workaround for "static data member not allowed in anonymous struct"
- Fix unresolved symbols in Python interface
- Use correct shared library suffix
- Force building shared libraries for Tcl interface
=> Fix compiling on Mac

src/core/CMakeLists.txt
More improvements to the recent build system changes. Unfortunately, it's still not fully working on my Mac.
This is what I get with CMake:
```
Linking CXX shared library libEspressoCuda.dylib
Undefined symbols for architecture x86_64:
"cuda_mpi_send_forces(float*, float*, CUDA_fluid_composition*)", referenced from:
copy_forces_from_GPU() in EspressoCuda_generated_cuda_common_cuda.cu.o
"cuda_mpi_get_particles(CUDA_particle_data*)", referenced from:
copy_part_data_to_gpu() in EspressoCuda_generated_cuda_common_cuda.cu.o
"copy_CUDA_energy_to_energy(CUDA_energy)", referenced from:
copy_energy_from_GPU() in EspressoCuda_generated_cuda_common_cuda.cu.o
"cuda_bcast_global_part_params()", referenced from:
p3m_gpu_init(int, int*, double, double*) in EspressoCuda_generated_p3m_gpu_cuda.cu.o …
```
=> More CUDA Cmake improvements

src/core/iccp3m.cpp, src/core/interaction_data.cpp, src/core/interaction_data.hpp, src/core/verlet.cpp, src/core/verlet.hpp
This will exclude pairs, which are more distant than short-range cutoff + skin
But still within coulomb and dipolar real space cutoff, if the particles both
don't carry charges/dipoles. This is done by excluding the dipolar/coulomb
part in ia_params[i,j].max_cut and storing them separately.
This results in performance and memory improvements for systems with only a small fraction
of particles carrying dipoles/charges.
=> More restrictive adding of pairs to verlet lists

scripts/blockfile_support.tcl, src/tcl/thermostat_tcl.cpp
Reading a langevin thermostat from a blockfile fails with:
thermostat langevin needs on/off
while executing
"thermostat langevin 1.0 1.0 0.0 1.0 1.0 "
The input routine expects: thermostat set langevin <temp> <gamma_trans> [<gamma_rot> <on/off> <on/off>]
So the print function should print "on" or "off" and not bools as doubles.
Also, remove the additional "{ off }".
=> Langevin print fix

cmake/MyConfig.cmake, src/core/electrokinetics_pdb_parse.hpp, src/core/tab.cpp, src/core/unit_tests/RunningAverage_test.cpp
- Use `configure_file` so that myconfig.hpp is copied at `make`-time and not just `cmake`-time
- Fix an `ifdef` mismatch between .cpp and .hpp file
- make the C++ code more standard-conforming
These changes were originally contained in #564, but it makes more sense to have them in a separate pull request.
=> Minor fixes for build system and compiling on Mac

scripts/vtf.tcl
writevcf would always print an additional 0 when printing particle data
of pid = 0. When using the userdata option, would not create an extra
column in the output.
=> Closes #659: fixed bug in writevcf

src/python/espressomd/analyze.pyx
Wrongly commented out code caused error when calling analyze.Vkappa(system, 'reset')
=> Bugfix Vkappa (Python Interface)

src/tcl/random_tcl.cpp
RANDOM_TRACE is always defined (see debug.hpp), so use RANDOM_DEBUG here.
=> Use RANDOM_DEBUG instead of RANDOM_TRACE

samples/python/visualization_bonded.py, src/python/espressomd/visualization.pyx
By cythonizing the inner loop in the update() method. Particle positions and bonds are accessed on the c level, avoiding python object construction.
Due to file rename .py -> .pyx, remove src/python under the build directory before recompiling.
=> Py: Speed up the mayavi visualization for large systems

CMakeLists.txt
- use python 2.* only
- use cython >=0.23
=> cmake: specify python version needed

samples/python/load_properties.py, samples/python/store_properties.py, src/python/espressomd/interactions.pyx
With this implementation all non-bonded interactions can be checkpointed via pickle.dump and pickle.load of system.non_bonded_inter:
* checkpointing of all nonbonded-inters set by "set_params()"
* checkpointing of forcecap
* sample script: extended store_properties.py and load_properties.py
=> Checkpointing NonBondedInteractions

testsuite/python/CMakeLists.txt, testsuite/tcl/CMakeLists.txt
We already agreed upon not using this feature a long time ago, as it marks skipped tests as failed. This was the reason we introduced the wrapper script for tests.
Needs to be removed because it's a feature of cmake 3.x, we require 2.8 as minimum.
=> testsuite: removed skip return code from cmake

CMakeLists.txt
since #749 with the use of the command `target_compile_definitions` we require 3.0
=> cmake: require version 3.0

doc/ug/introduction.tex
@RudolfWeeber, after @bindgens had so much trouble getting Espresso to compile on his Mac, I have added a few lines to the users guide on how to install the dependencies.
=> Add Mac install instructions to users guide

src/python/espressomd/particle_data.pyx
Particle creation is still explicit, i.e.
part[:].pos=0,0,0
only acts on existing particles.
=> Py: Make particle slicing work wit non-consecutive particle numbering

samples/python/minimal_random_number_generator.py, src/core/random.cpp, src/python/espressomd/_system.pxd, src/python/espressomd/_system.pyx
According to sackoverflow this seeding procedure is suggested:
https://stackoverflow.com/questions/15509270/does-stdmt19937-require-warmup 
```
std::seed_seq seeder{seed};
generator.seed(seeder);
```
seed_seq "tries to come up with a sane initialization" (see second source). 
However this is still not enough for a good seeding, see e.g. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0205r0.html#ref-01 or http://www.pcg-random.org/posts/cpp-seeding-surprises.html
Of course "good seeding" with only one 32bit integer cannot be done truely for the mersenne twister with its huge internal state which cannot be filled with only one 32bit integer. Maybe the most clean way to seed the mersenne twister in the core would be to provide a function set_random_seed() in the python interface …
=> Changed seeding of rng

scripts/blockfile_support.tcl
Do not use eval here, since it unpacks the list. The read function in
random_tcl.cpp, however, expects one string.
=> Fix t_random call in blockfile_read_auto_random

src/python/espressomd/electrostatics.pyx
Gone back to the old order because P3M wasn't tuning anymore with this one.
What doesn't work with this is sth like this:
```
p3m.validate_params()
p3m._set_params_in_es_core()
outParams = p3m.get_params() 
#this failes because python_p3m_set_params resets
#parameters in the core if l_bjerrum has not been set 
```
We also need a python testcase that involves tuning.
=> Revert initialization order in P3M Interface

src/python/espressomd/constraints.py, src/python/espressomd/script_interface.pyx, src/python/espressomd/shapes.pxd, src/python/espressomd/shapes.py, src/python/espressomd/shapes.pyx, src/script_interface/constraints/Constraint.hpp
* Adds ScriptInterfaceHelper-class wich allows to define
py objects which will instanciate as a given base class of PScriptInterface
class Wall(ScriptInterfaceHelper):
_so_name="Shapes::Wall"
* Adds Constraints class with add and remove methods
* Added py Constraint base class
* Added py Shape classes
* makes naming "params" consistent with rest of py interface
Usage example:
from espresomd.shapes import Wall
c=system.constraints.add(
shape=Wall(normal=[1,1,1],distance=1),particle_type=1)
print c.get_params()
This is still a preliminary solution.
=> Py: Front-end to constraints based on script interface

src/core/EspressoSystemInterface_cuda.cu, src/core/actor/DipolarDirectSum_cuda.cu, src/core/actor/HarmonicOrientationWell_cuda.cu, src/core/actor/HarmonicWell_cuda.cu, src/core/actor/Mmm1dgpuForce_cuda.cu, src/core/cuda_init_cuda.cu, src/core/electrokinetics_cuda.cu, src/core/fd-electrostatics_cuda.cu, src/core/immersed_boundary/ibm_cuda.cu, src/core/integrate_sd_cuda.cu, src/core/integrate_sd_cuda_debug.cu, src/core/integrate_sd_cuda_device.cu, src/core/integrate_sd_cuda_kernel.cu, src/core/integrate_sd_matrix.cu, src/core/lb-boundaries.hpp, src/core/lbgpu_cuda.cu, src/core/p3m_gpu_cuda.cu, src/core/p3m_gpu_error_cuda.cu
@fweik @RudolfWeeber @trau @rempferg 
_constraints.hpp_ included, by means of a very long dependency chain, _boost/mpi/communicator.hpp_.
=> Remove boost::mpi dependency in CUDA code

doc/ug/introduction.tex
**tl;dr** Don't use underscores in `\label`.
The user guide used to not compile on the first try with an error message like this
````
! Missing \endcsname inserted.
<to be read again> 
\unhbox 
l.23 ... on Ubuntu 16.04 LTS}{subsection.1.5.1}{}}
````
This is due to the fact that someone used an underscore in a `\label`.  The user guide does `\usepackage[strings]{underscore}`.  This package will make the underscore an active character, such that you can conveniently type text containing underscores without having to escape them using `\_` while retaining the meaning as the subscript operator in math mode.  Unfortunately, the definition of the macro behind the active underscore is not e-TeX protected which leads to it being expanded once written to an `aux` file (which is what `\label` …
=> Make the User guide compile again

.travis.yml, maintainer/docker/ubuntu-cuda/Dockerfile, maintainer/travis/build_cmake.sh, maintainer/travis/build_docker.sh, src/core/immersed_boundary/CMakeLists.txt, src/core/unit_tests/RunningAverage_test.cpp, src/core/utils/statistics/RunningAverage.hpp, src/tcl/CMakeLists.txt
This pull request adds the following build environments to Travis:
- Mac OS X 10.11 with LLVM 3.8 and Python 2.7
- Mac OS X 10.11 with LLVM 3.8 and Python 3
- Ubuntu 14.04 with GCC 4.8 and CUDA 7.5
@fweik will need to add ` maintainer/docker/ubuntu-cuda/Dockerfile` to the Espresso Docker Hub as `buildenv-espresso-ubuntu-cuda` before the CUDA build will work.
We obviously can't test CUDA code on Travis, but compiling it should help spot the biggest problems already. #851 would have never occurred if we had automatically built the CUDA code.
=> Travis: Build+test on Mac OS X and build CUDA code

CMakeLists.txt, maintainer/travis/build_docker.sh
FindPythonLibs.cmake appears to be broken, even more so in older CMake versions. There are many situations where it uses libraries and headers that don't match the interpreter used. This pull request uses `distutils.sysconfig` to directly obtain the header path from Python.
We don't need the library path because we are not embedding a Python interpreter into a C++ program, we are only creating a Python module. We did link the library before, but it's not necessary and not even considered good practice.
Closes #869.
=> Fix Python include path detection

src/python/pypresso.cmakein, src/python/pypresso.in
@richter-t complained about the difficulty of running Espresso with Python in the debugger. This pull request adds a flag `--gdb` to pypresso to simplify that as discussed with @RudolfWeeber. Obviously, you need to set `CMAKE_BUILD_TYPE=Debug` via ccmake.
=> Add --gdb flag to pypresso to launch Python in GDB

src/python/espressomd/reaction.pyx
Homebrew now ships version 0.25 of Cython.  There the behaviour of relative imports has changed which leads to an error when generating C++ code.  This commit merely replaces the offending line.
=> Relative import behaviour changed in Cython 0.25

maintainer/travis/build_cmake.sh
Fixes #922
- Uncommenting pep8 python file checks
=> Uncomment pep8 check in build script.

maintainer/docker/debian/Dockerfile, maintainer/docker/opensuse/Dockerfile, maintainer/docker/ubuntu-cuda/Dockerfile, maintainer/docker/ubuntu-python3/Dockerfile, maintainer/docker/ubuntu/Dockerfile
- Additional python package for h5 files in the dockerfiles
- Removing wrong packages in ubuntu-cuda Dockerfile
Is related to PR: #745
=> Add h5py package to Dockerfiles (needed for testing h5mdcore.

src/core/Vector.hpp, src/core/constraints.hpp, src/core/correlators/Correlator.cpp, src/core/observables/Observable.cpp, src/core/unit_tests/NumeratedContainer_test.cpp, src/core/unit_tests/Vector_test.cpp, src/core/utils/NumeratedContainer.hpp, src/core/utils/ObjectId.hpp, src/core/verlet.cpp, src/python/espressomd/script_interface.pxd, src/python/espressomd/script_interface.pyx, src/script_interface/ParallelScriptInterface.hpp, src/script_interface/Parameter.hpp, src/script_interface/ScriptInterface.hpp, src/script_interface/ScriptInterfaceBase.hpp, src/script_interface/Variant.cpp, src/script_interface/Variant.hpp, src/script_interface/VariantTester.hpp, src/script_interface/constraints/Constraint.hpp, src/script_interface/correlators/Correlator.hpp, src/script_interface/initialize.cpp, src/script_interface/lbboundaries/LBBoundary.hpp, src/script_interface/shapes/Cylinder.cpp, src/script_interface/shapes/Pore.cpp, src/script_interface/shapes/Rhomboid.cpp, src/script_interface/shapes/Sphere.cpp, src/script_interface/shapes/SpheroCylinder.cpp, src/script_interface/shapes/Wall.cpp, testsuite/python/correlation.py, testsuite/python/variant_conversion.py
- Made the variant type in the script interface recursive, so that functions can return structured data
- Corresponding translation functions in python
- some clean up of the ObjectId handling (needs further improvement)
- Cleanup and fix of the variant conversion
Fixes #889, #856, #855, #854,
=> Recursive variant

src/python/espressomd/analyze.pyx
Calling the method `espressomd.System.analysis.calc_rg()` failed, since it internally tried to call   `check_topology()` with the undefined parameter `system`.
=> Make calc_rg work in the python interface

src/python/espressomd/visualizationMayavi.pyx
Usually, particles are visualized according to their Lennard-Jones radius.  This is a slight drawback because this requires a LJ interaction of particles with the same type.  If this is not desirable for physical reasons these particles cannot be visualized.  Therefore we overload the visualizer in such a way that the user can define a custom mapping function from type to particle radius.  If this overload is not used it defaults to the previous behavior.
Example:  Set the radius for all particles (all types) to 0.5
````
visualizer = visualization.mayaviLive(system, lambda x: 0.5)
````
=> Add custom mapping for particle visualization.

src/python/espressomd/script_interface.pyx
Fixes #935 
- Implicitly convert ints to double when setting parameters
PR Checklist
------------
=> script_interface: Accept ints for double parameters.

src/python/espressomd/particle_data.pyx
- if the mass feature is not compiled in the mass atribute is removed from the __getstate__ method otherwise the __setstate__ method would try to set the mass which is not supported.
=> pickle: only pickle the mass if its compiled in.

src/python/espressomd/utils.pyx
`handle_errors` gets all the runtime errors from the core and propagates them to the Python level, converting them to proper Python exceptions.  However, the last branch of the code
````
if not errors.empty() :		
raise Exception(msg)
````
does not check whether the error is an actual error or only a warning.  This leads to funny problems with the LB.  In the first step LB has to recalculate all the coupling forces for obvious reasons.  This is signalled as a RuntimeWarning.  If one now calls another routine which calls `handle_errors` (e.g. `analysis.energy`) this RuntimeWarning will be caught and converted into an exception due to this last branch.  I don’t think this is intended and therefore I removed this branch.  If the error is of class RuntimeError and exception will still be …
=> You won’t believe why my simulation failed.

src/python/espressomd/visualization.pyx
@KonradBreitsprecher: Thischange  allows using one visualizer if the other's dependencies are not met. Previously, the following would fail if mayavi wasn't installed: 
```
from espressomd.visualization import openGLLive
```
=> Defer visualizer import errors to when visualizer is instantiated

src/core/particle_data.cpp
Compiling without `PARTICLE_ANISOTROPY` was no longer possible.  With `PARTICLE_ANISOTROPY` one encountered errors à la
````
ValueError: Friction has to be 3 floats -- A single value was given but 3 were expected.
````
in previously working simulation code.
=> Corrected wrong ifdefs

.travis.yml
The false positives are annoying. They can be re-enabled when the boost build on osx is fixed.
=> travis: Disabled OSX tests.

CMakeLists.txt, doc/ug/io.tex, doc/ug/setup.tex, samples/python/h5md.py, samples/python/minimal-polymer.py, src/core/io/writer/h5md/h5md_core.cpp, src/core/io/writer/h5md/h5md_core.hpp, src/core/particle_data.cpp, src/python/espressomd/CMakeLists.txt, src/python/espressomd/io/writer/h5md.py, src/python/espressomd/script_interface.pyx, src/script_interface/h5md/h5md.cpp, testsuite/python/h5md.py
I made H5MD output standard conform (the dimensionality of the datasets that were written was in some cases wrong). Further I added fast ordered output for h5md from the master node only. In the case of having tons of particles the output might be faster with the option write_ordered=false which performs writing in parallel on all nodes, however data is not sorted according to ids.
=> H5 md serial output on head parallel

src/core/unit_tests/CMakeLists.txt
Up until now it was not possible to declare more than one source file in the `unit_test` interface.  One had to help oneself with constructions like
````cmake
set(simple_test_SRC source1.cpp source2.cpp)
unit_test(simple_test "${simple_test_SRC}")
````
Furthermore there was an extra interface for MPI parallel unit tests, even though both variants only differ in their call signature (with or without `mpiexec`).  Using the function [`cmake_parse_arguments`](https://cmake.org/cmake/help/v3.0/module/CMakeParseArguments.html), I unified these two variants and made it possible to list the sources directly in the function arguments.  What was before
````cmake
set(ParallelScriptInterface_test_SRC  ParallelScriptInterface_test.cpp)
parallel_unit_test(ParallelScriptInterface_test …
```
=> You won’t believe how this guy improved the build system

maintainer/travis/build_cmake.sh
This gives a speedup of several minutes for the builds.  Compare [Build 1722][1722] with [Build 1723][1723]:
| Build 1722    | Build 1723    |
|---------------|---------------|
| 8 min 33 sec  | 7 min 27 sec  |
| 10 min 53 sec | 7 min 57 sec  |
| 10 min 13 sec | 8 min 2 sec   |
| 10 min 21 sec | 8 min 42 sec  |
| 15 min 11 sec | 12 min 11 sec |
| 30 min 52 sec | 17 min 35 sec |
| 39 min 2 sec  | 18 min 7 sec  |
| 9 min 26 sec  | 7 min 59 sec  |
| 9 min 8 sec   | 8 min         |
| 9 min 57 sec  | 7 min 53 sec  |
| 8 min 1 sec   | 7 min 9 sec   |
| 9 min 44 sec  | 6 min 54 sec  |
| 8 min 57 sec  | 7 min 2 sec   |
[1722]: https://travis-ci.org/espressomd/espresso/builds/202585126
[1723]: https://travis-ci.org/espressomd/espresso/builds/202601995
=> Travis has two cores.  Why don't we use them?

cmake/FindSphinx.cmake
sphinx: remove FATAL_ERROR from FindSphinx.
=> Even click-bate PR writers are surprised by this little hack.

CMakeLists.txt, src/core/CMakeLists.txt, src/core/actor/CMakeLists.txt, src/core/immersed_boundary/CMakeLists.txt, src/core/object-in-fluid/CMakeLists.txt, src/core/scafacos/CMakeLists.txt
Espresso is a python module now, so .so versioning is not needed
anymore. Move all libraries into python module path as well.
=> cmake: remove soversion

src/core/lb.cpp, src/core/lbgpu.hpp, src/core/lbgpu_cuda.cu, src/python/espressomd/lb.pxd, src/python/espressomd/lb.pyx, src/python/pypresso.cmakein
So far directly setting the populations on the LB lattice nodes was only possible for LB on the CPU.  This PR introduces this feature for the GPU.
Note:  Because SHANCHEN is not yet interfaced, it is not clear what the behaviour for a multi-component fluid should be.  We ensure extensibility by providing a default parameter for the fluid component, which defaults to 0 (which is the case without SHANCHEN).
=> Don’t click this if you don’t want to set LB populations

doc/ug/otherrefs.bib, doc/ug/run.tex
The source code refers to
http://ciks.cbt.nist.gov/~garbocz/dpd1/dpd.html that is actually the web
version of the (now-)cited article.
There is no corresponding issue number.
- Addition of a reference and of a comment about quaternion based-integration in the section "integrate".
PR Checklist
------------
=> add reference to martys99 for quaternions integrator

CMakeLists.txt
This is useful on HPC machines, where the python install location does not necessarily follow the standard FHS conventions.
=> cmake: allow user to override PYTHON_INSTDIR

src/core/Vector.hpp, src/script_interface/ScriptInterfaceBase.hpp
Instead of having separate specializations for `Vector2d`, `Vector3d`, etc. in `ScriptInterfaceBase.hpp` this PR proposes template overloads based on [SFINAE](http://en.cppreference.com/w/cpp/language/sfinae) which choose a different implementation at compile time for *all* instantiations of the `Vector` class template.
=> Merge this PR and ESPResSo will never be the same again

src/core/communication.cpp
Remove obsolete "reorder" variable. It was made obsolete in mpi_init by the introduction of mpi_reshape_communicator.
=> Remove unnecessary variable
