src/tcl/statistics_observable_tcl.cpp
The way the parsing was done, there was an inherent threat to end in an infinite loop. Just very minor changes to avoid this.
=> Tcl Parser for polymer observables

scripts/object_in_fluid.tcl
Hello.
Because of recent discussion on the users' mailing list, I have updated the error messages in the object-in-fluid framework so that they are more informative.
Please, merge. Thank you,
Iva Jancigova
=> fixed error messages

doc/ug/setup.tex, src/core/communication.cpp, src/core/communication.hpp, src/core/integrate.cpp, src/core/thermostat.cpp, src/core/thermostat.hpp, src/tcl/thermostat_tcl.cpp
This pull request implements a CPU thermostat. This gives Espresso the ability to thermalize the CPU, which is quite a unique feature in MD simulation software, which typically only allows for thermalization of the objects simulated (particles, fluids, ...), but not of the hardware running the simulation.
=> CPU Thermostat

doc/ug/run.tex, src/core/metadynamics.cpp, src/core/metadynamics.hpp, src/tcl/metadynamics_tcl.cpp
The Metadynamics algorithm did not include the relaxation steps which are needed. See the following literature for reference.
Laio, Alessandro, and Francesco L. Gervasio. "Metadynamics: a method to simulate rare events and reconstruct the free energy in biophysics, chemistry and material science." Reports on Progress in Physics 71.12 (2008): 126601.
=> Changed Metadynamics Algorithm, added relaxation steps

doc/ug/part.tex
=> Made documentation for part gc feature more clear

src/core/pressure.cpp, src/core/pressure.hpp, src/core/statistics.cpp, src/python/espressomd/analyze.pyx, src/python/espressomd/c_analyze.pxd
This adds pressure and nbhood to the python interface. I did my best to dump the logic from pressure_tcl.cpp into cpp files.
=> Python pressure

doc/ug/inter.tex, src/python/espressomd/interactions.pyx, src/python/espressomd/particle_data.pyx
Added function: BondedInteractions.add(bond)
Added function: part.addBond(bond, partner)
old functions bondedInter[id]=interaction &
addBond(bond) [bond in this case list of 2-tuples)
not yet removed
=> Remove bond ids

src/python/espressomd/interactions.pxd, src/python/espressomd/interactions.pyx, testsuite/python/nonBondedInteractions.py
Included the non-bonded Generic Lennard Jones interaction in the python interface.
=> Generic Lennard Jones

src/core/statistics_correlation.cpp, src/tcl/statistics_wallstuff_tcl.cpp
=> Fix compiling with Clang on Mac

doc/ug/part.tex, doc/ug/run.tex, src/core/tuning.cpp, src/core/tuning.hpp, src/tcl/initialize_interpreter.cpp, src/tcl/tuning_tcl.cpp
Determine optimal skin by bisection.
=> Tune skin command

doc/ug/part.tex
See also https://github.com/espressomd/espresso/pull/377
=> Added missing parameter to pore constraint docu

src/core/communication.cpp, src/core/lb.cpp, src/core/lb.hpp, src/tcl/lb_tcl.cpp, testsuite/virtual-sites-rotation.tcl, testsuite/virtual-sites.tcl
jz mode fluctuation not properly initialized
odd/even modes were assigned wrong fluctuation (zero)
population output incorrect for SHANCHEN
gamma_even input parser wrong
=> Espresso md

testsuite/virtual-sites-rotation.tcl
The shortened version of the test still complies with the requested accuracy, takes much less time to execute (this should help travis checks to run faster), and tests multiple particles. See issue https://github.com/espressomd/espresso/issues/388
=> shortened the virtual-sites-rotation.tcl test

doc/ug/part.tex, src/core/Vector.hpp, src/core/config.hpp, src/core/unit_tests/Vector_test.cpp
=> Fix C++11 stuff and clean up vector class

configure.ac, maintainer/jenkins/build.sh, maintainer/run_multiconfig.sh
=> Remove hardcoded gnu c++ implementation from build system

src/core/domain_decomposition.cpp, src/core/energy_inline.hpp, src/core/forces.cpp, src/core/forces_inline.hpp, src/core/layered.cpp, src/core/nsquare.cpp, src/core/verlet.cpp
Also (undocumented) external_potential now need EXTERNAL_FORCES feature.
=> Centralized single particle contributions to force and energy.

src/core/communication.cpp
Partially fixes #404.
Somehow the object file gets loaded twice: once before `mpi_init` and once after. This results in the global variables being reset to zero.
=> Fix MPI callback mechanism when used with Python

testsuite/Makefile.am, testsuite/langevin_per_particle.tcl, testsuite/mass-and-rinertia_per_particle.tcl
Added testcases for LANGEVIN_PER_PARTICLE
=> Testcase langevin per particle

samples/python/bonds-tst.py, samples/python/coulomb_debye_hueckel.py, samples/python/debye_hueckel.py, samples/python/lj_liquid.py, samples/python/minimal-charged-particles.py, samples/python/minimal-polymer.py, samples/python/p3m.py, src/core/communication.cpp, src/core/particle_data.cpp, src/core/particle_data.hpp, src/python/espressomd/electrokinetics.pyx, src/python/espressomd/particle_data.pxd, src/python/espressomd/particle_data.pyx, testsuite/python/bondedInteractions.py, testsuite/python/particle.py
=> Py particle iterator and explicit particle creation

src/core/collision.cpp, src/core/communication.cpp
Correct a bug and get rid of a format specifier related warning.
=> Two small printf type fixes

src/python/CMakeLists.txt, src/python/pypresso.cmakein
=> Pypresso amend

testsuite/CMakeLists.txt, testsuite/python/CMakeLists.txt
rudimentary, mpi support is commented out right now,
python tests are not fully supported
=> Cmake make check and make check_py

src/core/CMakeLists.txt, src/core/electrostatics/CMakeLists.txt, src/core/electrostatics/scafacos/CMakeLists.txt
=> cmake: Fix build with scafacos.

src/core/mpiio.cpp
... and remove some whitespace.
=> Fix segfault in MPI-IO

src/core/lb.cpp
This should fix the realloc problem with swapping populations in LB
=> fixed reallog bug in LB

doc/ug/setup.tex
% puts [setmd piston]
unknown md variable "piston"
=> Correction of wrong md variable piston in ug

scripts/h5md.tcl, src/core/mmm1d.cpp
=> added sanity check before tuning in mmm1d starts

.travis.yml, CMakeLists.txt, NEWS, scripts/blockfile_support.tcl, src/core/communication.cpp, src/core/communication.hpp, src/core/random.cpp, src/core/random.hpp, src/tcl/random_tcl.cpp
With this pull request Espresso depends on boost mpi. Closes #577
=> Reimplemented checkpointing for RNG

.travis.yml, CMakeLists.txt, src/core/CMakeLists.txt, src/core/RuntimeError.cpp, src/core/RuntimeError.hpp, src/core/RuntimeErrorCollector.cpp, src/core/RuntimeErrorCollector.hpp, src/core/RuntimeErrorStream.hpp, src/core/errorhandling.cpp, src/core/errorhandling.hpp, src/core/integrate.cpp, src/core/unit_tests/CMakeLists.txt, src/core/unit_tests/RuntimeErrorCollector_test.cpp, src/core/unit_tests/RuntimeError_test.cpp, src/python/espressomd/integrate.pxd, src/python/espressomd/integrate.pyx, src/tcl/parser.cpp, testsuite/tcl/CMakeLists.txt
=> Fix warnings

src/core/Makefile.am, src/core/scafacos.cpp, testsuite/tcl/coulomb_cloud_wall.tcl
=> P3m sanity check

src/python/CMakeLists.txt, src/python/espressomd/CMakeLists.txt
This should make sure that if you change anything in the python src dir, cmake detects it.
=> Pxd depends

doc/ug/analysis.tex, samples/python/lj_liquid_distribution.py, src/python/espressomd/analyze.pyx, src/python/espressomd/c_analyze.pxd, src/python/espressomd/utils.pyx
implementation was tested with samples/python/lj_liquid_distribution.py
=> Implementation and Documentation of espressomd.analyze.distribution()

doc/ug/analysis.tex, samples/python/coulomb_debye_hueckel.py, samples/python/debye_hueckel.py, samples/python/electrophoresis.py, samples/python/lbf.py, samples/python/lj-demo.py, samples/python/lj_liquid.py, samples/python/lj_liquid_distribution.py, samples/python/lj_liquid_structurefactor.py, samples/python/load_properties.py, samples/python/minimal-charged-particles.py, samples/python/minimal-diamond.py, samples/python/minimal-polymer.py, samples/python/p3m.py, samples/python/slice_input.py, samples/python/store_properties.py, samples/python/visualization.py, src/python/espressomd/_system.pyx, src/python/espressomd/analyze.pyx, testsuite/python/minimize_energy.py
To avoid passing system to every single call of an analysis method.
Also make analysis available via ana property of System class.
This includes the interface itself, testcases, sample scripts and user guide.
=> Py: Move analysis routines into a class

samples/python/slice_input.py
=> fixed slice_input.py

samples/python/store_properties.py, src/python/espressomd/particle_data.pyx
=> particle key_list fix

doc/ug/oif.tex, scripts/object_in_fluid.tcl
This is useful for people who work with object-in-fluid framework to evaluate the quality of meshes they are trying to use. Please, merge.
Thank you.
Iva
=> added edge statistics for meshes used by object-in-fluid

doc/ug/firststeps.tex, doc/ug/introduction.tex
No build docs, no integrator docs
=> Py: Introduction and First steps chapter (partial)

src/python/espressomd/particle_data.pyx
The tcl-function 'writevtk' is now ported to python.
=> Write Particles to VTK-File -- system.part.writevtk()

samples/python/load_properties.py, samples/python/store_properties.py
added with statement for correct file closing in the pickle sample files
=> replaced syntax

doc/ug/setup.tex, src/python/espressomd/Makefile.am, src/python/espressomd/_system.pyx, src/python/espressomd/galilei.pxd, src/python/espressomd/galilei.pyx
Galilei transformation for the python interface
=> Galilei transform

src/python/espressomd/particle_data.pyx
=> redesigned exclusions and added slice input

doc/tutorials/tcl/01-lennard_jones/01-lennard_jones.tex, doc/tutorials/tcl/01-lennard_jones/scripts/lj_functions.tcl, doc/tutorials/tcl/01-lennard_jones/solutions/lj_functions.tcl, doc/ug/io.tex, packages/mbtools/examples/scripts/main.tcl, packages/mbtools/utils/warmup.tcl
=> removed bitrandom and bitseed

scripts/h5md.tcl, src/tcl/h5mdfile_tcl.cpp
Sorry, I do not know how my changes have reverted this.. Maybe issue of the back-merging.
This pull request is a restoration of the original commits made by @KaiSzuttor 
I will make my branching strategy more conventional to avoid such cases in future.
=> Restoration of the commits 9e82b7b and 14d3657

doc/ug/part.tex, src/core/constraint.cpp, src/core/constraint.hpp, src/core/interaction_data.hpp, src/tcl/constraint_tcl.cpp
Removing old command, see #753
=> purged plane constraint

doc/tutorials/python/08-visualization/08-visualization.tex, doc/tutorials/python/08-visualization/CMakeLists.txt, doc/tutorials/python/08-visualization/scripts/plotting.py, doc/tutorials/python/08-visualization/scripts/simulation.py, doc/tutorials/python/08-visualization/scripts/visualization.py, doc/tutorials/python/CMakeLists.txt
=> Python Visualization tutorial

doc/tutorials/python/01-lennard_jones/01-lennard_jones.tex, doc/tutorials/python/01-lennard_jones/refs.bib
I sorted out the structure, removed duplicate stuff, added some explanations, removed tcl remnants and made some corrections.
=> Work on python lj tutorial.

doc/tutorials/tcl/01-lennard_jones/01-lennard_jones.tex, doc/tutorials/tcl/04-lattice_boltzmann/latex/diffusion.tex, doc/tutorials/tcl/04-lattice_boltzmann/latex/dragforce.tex, doc/tutorials/tcl/04-lattice_boltzmann/latex/interface.tex, doc/tutorials/tcl/04-lattice_boltzmann/latex/intro.tex, doc/ug/analysis.tex, doc/ug/inter.tex, doc/ug/lb.tex, doc/ug/oif.tex, doc/ug/part.tex, doc/ug/run.tex
Replace \bf -> \textbf, \tt -> \texttt, \it -> \textit
\rm -> \textrm
=> doc: make it work with texlive-2016 (fixes #768)

samples/python/minimal_random_number_generator.py, src/core/random.cpp, src/core/random.hpp, src/python/espressomd/_system.pxd, src/python/espressomd/_system.pyx, src/tcl/random_tcl.cpp
pickle should now in principle be able to get and set the random number generator state in the core.
=> added python interface for core random number generator

scripts/h5md.tcl
Removes Memleak since wrong data space identifier was closed previously.
=> H5mdtclfix

src/core/MpiCallbacks.cpp, src/core/communication.cpp, src/core/utils/serialization/array.hpp
=> utils: Added serialiaztion routine for std::array

doc/ug/lb.tex, samples/python/lbf.py, src/core/lb.cpp
=> Py lbfluid

src/python/espressomd/interactions.pyx
=> added params update implicit

src/core/interaction_data.cpp, src/python/espressomd/interactions.pxd, src/python/espressomd/interactions.pyx, src/python/espressomd/utils.pyx, testsuite/tcl/test_wrapper.py
These changes were present in 5b0909bcbcbd8cf5c4f7ca8ea0b30238c167287e, but got lost in 6daf4e85da43c3891ec25f2e711799b975d23ae0
Closes #826
=> Fix tests with Python 3

doc/ug/aux.tex, doc/ug/io.tex, samples/python/minimal_random_number_generator.py, src/python/espressomd/_system.pyx
added documentation for random number generator functions in python and tcl
=> random number generator

doc/tutorials/python/00-building_espresso/00-building_espresso.tex, doc/tutorials/python/00-building_espresso/CMakeLists.txt, doc/tutorials/python/CMakeLists.txt
adjusting tcl tutorial 00 to cmake and python, @RudolfWeeber - could you please merge this also in you python branch for the es summer school?
=> Python Tutorial 00: Building Espresso

doc/ug/setup.tex
=> ug update: python analog of the setmd command

src/core/immersed_boundary/ibm_cuda_interface.cpp
=> Fix build w/ IMMERSED_BOUNDARY

maintainer/travis/build_docker.sh
@fweik, this should fix it.
Once this builds, I will cherry-pick to the python branch and create another pull request.
=> Fix Travis Mac builds after build environment changes

src/python/espressomd/correlators.py, src/python/espressomd/particle_data.pyx, src/python/espressomd/script_interface.pyx
Fixes #924
- Make indentation in python files multiple of 4
=> Fixing indentation in python interface.

maintainer/jenkins/build_cmake.sh
Small changes to the build_cmake script to make everything work.
=> Added new cmake builds to Jenkins

src/core/rotation.cpp
Fixes #
- 
PR Checklist
------------
=> Rot iteration fix for python branch

src/python/espressomd/visualizationOpenGL.py
Fixes #972 
- Removed osascript invocation in OpenGL visualization.
=> Remove "hac" for mac

src/python/espressomd/CMakeLists.txt
=> Fixing cython issue on second build (import local module io).

src/python/CMakeLists.txt, src/python/pypresso.cmakein
Generate an ipypresso script for interactive sessions (supports 'ipypresso notebook')
This is good for demonstration purposes and for people who like autocompletion.
=> Keyboard vendors hate this PR!

src/tcl/thermostat_tcl.cpp
=> Issue warning when attempting to overwrite thermostat

src/python/espressomd/thermostat.pyx
=> This bug fix will blow your mind!

doc/sphinx/part.rst
Description of how to add and delete particles plus how to set and get particle properties.
=> Sphinx Setting Up Particles

cmake/FindSphinx.cmake, doc/sphinx/CMakeLists.txt, doc/sphinx/run.rst, src/python/espressomd/integrate.pyx
=> [sphinx] Running the simulation

src/python/espressomd/thermostat.pyx
=> Exposed!  Simple life hack for a single thermostat

src/core/actor/DipolarDirectSum.cpp, src/core/actor/DipolarDirectSum.hpp
Fixes #
- 
PR Checklist
------------
=> DDS-GPU Bjerrum assignment correction

.travis.yml, maintainer/travis/build_docker.sh, src/core/communication.cpp
Fixes #991. Please also merge to python branch.
Note that this depends on https://github.com/Homebrew/homebrew-core/pull/9598, so wait until that one is merged.
=> Travis: Use boost-mpi from Homebrew

src/python/espressomd/_system.pyx
=> Mindblowing floating point comparison life hack!

src/python/espressomd/analyze.pyx
=> Bonded energy was always zero

doc/sphinx/io.rst, samples/python/h5md.py, src/core/io/writer/h5md/h5md_core.cpp, src/core/io/writer/h5md/h5md_core.hpp, src/python/espressomd/io/writer/h5md.py, src/script_interface/h5md/h5md.cpp, src/script_interface/h5md/h5md.hpp, src/script_interface/h5md/initialize.hpp, testsuite/python/h5md.py
=> H5md proposol conform

src/python/espressomd/_system.pyx, src/python/espressomd/utils.pxd
=> [python] Hopefully better comparison for time_step
